export const ATTEMPT_REPOSITORY = Symbol('ATTEMPT_REPOSITORY');
export const ATTEMPT_SERVICE = Symbol('ATTEMPT_SERVICE');

export const CREATE_ATTEMPT_USECASE = Symbol('CREATE_ATTEMPT_USECASE');
export const GET_ATTEMPTS_USECASE = Symbol('GET_ATTEMPTS_USECASE');
export const RESOLVE_ATTEMPT_USECASE = Symbol('RESOLVE_ATTEMPT_USECASE');
